### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by davideanderson** [aro1976/aws-parent#6]
I like what you've done with your project, and I would like to take it and make a few tweaks for my own project.   However, I don't see a license, so I don't know if there are any restrictions on how I can use it.

**Comment by aro1976** [comment]
David,

Feel free to do whatever you want, I plan to release it under a BSD like license, but please tell me what kinds of improvements you're trying to develop?

Regards,
Alessandro

Enviado via iPhone

Em 21/03/2013, às 11:51, David Anderson notifications@github.com escreveu:

**Comment by davideanderson** [comment]
There are a couple of things...  

First, rather than use only the digest as the name on s3, I would want to retain the original name (helps with debugging and such).  So, instead of the name being [digest], I would make it something like /[digest]/original/path/original_name.js.gz.  That way, the digest still does its job with regards to browser caching and such, but we still retain the original resource information as well.

Second, I would like to modify the jsp tag so that it behaves differently for development environments.  For a dev environment, it could still access static resources via local, relative paths, and only use the uploaded versions during QA and production environments.

Third, I would also like to figure out a way to separate the creation of the manifest from the actual upload.  That way, we can package up a production war, but not necessarily deploy it at that time, nor do the upload.  Then, when we do deploy it, we could also run the upload.  That adds in a bit of risk that the manifest may change between the package and the upload, but if that becomes a huge concern, it could be solved by uploading the manifest along with all the rest, and then the app could use that version of the manifest.  

Finally, currently, some of our resources are packaged up into a jar file.  I am trying to decide if I want to try to extract all the files from the jar file, or modify the plugin so that it can search the jar files for resources as well.

Obviously, I still have some thinking to do, but that gives you an idea of some of the issues I am trying to solve.

**Comment by davideanderson** [comment]
Oh, and one more issue for which I don't have a solution yet:  How to clean up old versions from s3?  New versions get uploaded, but old versions are never removed.  I could remove them manually, if I could tell if they were old and not used.... but how to tell?

**Comment by aro1976** [comment]
would you please open these issues separated using https://github.com/aro1976/aws-parent/issues/new, I have already addressed some of them, and there are some workarounds that can be done, but they are actually not documented.

Em 22/03/2013, às 16:38, David Anderson notifications@github.com escreveu:
